# Generated by Django 5.2.1 on 2025-08-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('Option_a', models.TextField()),
                ('Option_b', models.TextField()),
                ('Option_c', models.TextField()),
                ('Option_d', models.TextField()),
                ('Correct_ans', models.TextField()),
            ],
        ),
    ]
