# Generated by Django 5.2.1 on 2025-08-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Correct_ans',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_a',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_b',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_c',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Option_d',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.CharField(max_length=400),
        ),
    ]
