# Generated by Django 5.2.1 on 2025-08-27 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_questions_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='Staff',
        ),
    ]
