# Generated by Django 5.2.1 on 2025-08-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_remove_questions_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=255)),
                ('phone_num', models.CharField(max_length=20)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.staff')),
            ],
        ),
    ]
