# Generated by Django 5.2.1 on 2025-09-05 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=400)),
                ('Option_a', models.CharField(max_length=300)),
                ('Option_b', models.CharField(max_length=300)),
                ('Option_c', models.CharField(max_length=300)),
                ('Option_d', models.CharField(max_length=300)),
                ('Correct_ans', models.CharField(max_length=300)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.staff')),
            ],
        ),
    ]
