# Generated by Django 5.2.1 on 2025-09-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_students_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
