# Generated by Django 5.2.1 on 2025-09-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0010_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='Staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quiz.staff'),
            preserve_default=False,
        ),
    ]
