# Generated by Django 5.2.1 on 2025-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0011_students_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
