# Generated by Django 5.2.1 on 2025-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_remove_students_phone_num_students_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='took_test',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
