# Generated by Django 5.2.1 on 2025-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0013_students_took_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='took_test',
            field=models.BooleanField(default=False),
        ),
    ]
